export const _follow = [
  {
    id: 1,
    name: '200Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_1.jpg',
    description: 'I am a developer',
    types: 'follower',
  },
  {
    id: 2,
    name: '201Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_2.jpg',
    description: 'I am a developer',
    types: 'follower',
  },
  {
    id: 3,
    name: '400Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_3.jpg',
    description: 'I am a developer',
    types: 'following',
  },
  {
    id: 4,
    name: '404Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_4.jpg',
    description: 'I am a developer',
    types: 'following',
  },
  {
    id: 5,
    name: '403Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_1.jpg',
    description: 'I am a developer',
    types: 'follower',
  },
  {
    id: 6,
    name: '500Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_2.jpg',
    description: 'I am a developer',
    types: 'follower',
  },
  {
    id: 7,
    name: '400Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_3.jpg',
    description: 'I am a developer',
    types: 'following',
  },
  {
    id: 8,
    name: '203Lab',
    username: 'luisa',
    avatar: '/assets/images/avatars/avatar_4.jpg',
    description: 'I am a developer',
    types: 'following',
  },
];
